### ISSUE TITLE
Discord Integration not working with Flatpak Discord

### ISSUE THREAD

**Issue by okseb** [flathub/io.github.harmonoid.harmonoid#1]
I just installed Harmonoid and played a song and don't see my Discord status updating to reflect it. I believe this should be fixable if you follow this guide https://github.com/flathub/com.discordapp.Discord/wiki/Rich-Precense-(discord-rpc)#flatpak-applications

**Comment by alexmercerind** [comment]
Thanks a lot for giving a try to the app. I will definitely have a look & let you know soon.

**Comment by okseb** [comment]
> Thanks a lot for giving a try to the app. I will definitely have a look & let you know soon.

Yeah no problem, works great so far other than that which is obviously a minor issue.

Edit: oops didn't mean to close it

**Comment by alexmercerind** [comment]
Hey, sorry I have decided to take-down Flathub version now. Since I didn't author Flathub version, I just came to know about the limitations & major bugs that it introduced. We are now using completely separate set of dependencies & other progress has been made since then. Flatpak & stuff is too much for me right now & I don't want to focus on packaging/distribution, but rather on the development side of things.
